services:
  db:
    image: postgres:17.5-alpine3.22
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ecommerce_db
    volumes:
      - ./postgres:/var/lib/postgresql/data